default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", ENV["USER"]) %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "bitolando_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "bitolando_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PRODUCTION", "bitolando_production") %>
  username: <%= ENV.fetch("DB_USERNAME", "bitolando") %>
  password: <%= ENV["DB_PASSWORD"] %>
